routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

Route::get('/', function ($guard = null){
    if(Browser::isIE() || Browser::isEdge()){
        return view('auth/bad_browser');
    }elseif (Auth::guard($guard)->check()) {
        return redirect('/home');
    }
    else{
        return view('auth/login');
    }
});

Route::get('/bad_browser', function (){
    return view('auth/bad_browser');
})->name('bad.browser');

Auth::routes();

Route::group(['middleware' => ['web','auth'],'prefix'=>''], function (){
    Route::get('/home', 'HomeController@index')->name('home.index');
    Route::resource('settings', 'SettingsController');
    Route::resource('customer','CustomerController');
    Route::resource('invoice','InvoiceController');
    Route::post('/updatePassword', 'ResetPasswordController@updatePassword')->name('update.password');
    Route::post('/invoice/states/{id}/{page?}','InvoiceController@states')->name('invoice.states');
    Route::get('/livesearch', 'LiveSearchController@action')->name('live_search.action');
    Route::get('/export', 'ExportController@export')->name('invoice.export');
    Route::get('/vatValidator', 'vatValidatorController@action')->name('vatValidator.action');
    Route::get('/generate-html-to-pdf/{email?}', 'HtmlToPDFController@index')->name('generate-pdf');
    Route::get('/customer/showInvoice/{id}/{page?}', 'InvoiceController@show')->name('customer_show_invoice');
    Route::get('/customer/editInvoicing/{id}/{page?}', 'InvoiceController@edit')->name('customer_edit_invoice');
    Route::post('/customer/stateInvoice/{id}/{page?}', 'InvoiceController@states')->name('customer_states_invoice');
});

resources/views/editInvoicing.blade.php
<div id="appInvoice" class="sw_form row w-100 h-100 mt-4 d-flex flex-column">
    <form-invoice></form-invoice>
</div>

resources/views/home.blade.php
@extends('layouts.app')



@section('content')
<div class="home-container h-100 container-fluid">
    <div class="row w-100 h-100 d-flex flex-column justify-content-center">
        <div id="container-chart" class="row w-100 col-12 d-flex justify-content-center">
            <div class="h-100 col-6">
                <h5>Invoicing percentage</h5>
                <canvas id="invoicingPieChart"></canvas>
            </div>
            <div class="h-100 col-6">
                <h5>Total invoices and credit notes</h5>
                <canvas id="invoicingBarChart"></canvas>
            </div>
        </div>
    </div>

</div>
@endsection

resources/views/tab_billing.blade.php
<div class="table-responsive">
    <table id="table_invoicing" class="table_invoices table table-striped table-dark">
        <thead class="thead">
        <tr>
            <th>Type</th>
            <th>Invoice number</th>
            <th>Customer</th>
            <th>Date</th>
            <th>Inception date</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($invoices as $invoice)
                <tr class="draft table-row"
                    data-href="
                        @if(strpos(url()->current(), 'customer'))
                            {{ route('customer_show_invoice',['id'=>$invoice->invoice_id,'page'=>'customer']) }}
                        @else
                            {{ route('invoice.show',$invoice->invoice_id)}}
                        @endif"
                >
                    <td>{{ ucfirst($invoice->type->type_name) }}</td>
                    <td>{{ ucfirst($invoice->invoice_number) }}</td>
                    <td>{{ ucfirst($invoice->customer->first_name) }} {{ ucfirst($invoice->customer->last_name) }}</td>
                    <td>{{ date('d-m-Y', strtotime($invoice->date))}}</td>
                    <td>{{ date('d-m-Y', strtotime($invoice->created_at))}}</td>
                    <td class="status">
                        <span class="
                            @if($invoice->status_id === 7)
                                draft
                            @elseif($invoice->status_id === 4)
                                validated
                            @elseif($invoice->status_id === 2)
                                sent
                            @elseif($invoice->status_id === 1)
                                paid
                            @elseif($invoice->status_id === 8)
                                signed
                            @elseif($invoice->status_id === 3)
                                rejected
                            @elseif($invoice->status_id === 6)
                                deleted
                            @elseif($invoice->status_id === 9)
                                reminder
                            @endif
                        ">
                            {{ strtoupper($invoice->status->status_name) }}
                        </span>
                    </td>
                </tr>
        @endforeach
        </tbody>
    </table>
</div>