routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

Route::get('/', function ($guard = null){
    if(Browser::isIE() || Browser::isEdge()){
        return view('auth/bad_browser');
    }elseif (Auth::guard($guard)->check()) {
        return redirect('/home');
    }
    else{
        return view('auth/login');
    }
});

Route::get('/bad_browser', function (){
    return view('auth/bad_browser');
})->name('bad.browser');

Auth::routes();

Route::group(['middleware' => ['web','auth'],'prefix'=>''], function (){
    Route::get('/home', 'HomeController@index')->name('home.index');
    Route::resource('settings', 'SettingsController');
    Route::resource('customer','CustomerController');
    Route::resource('invoice','InvoiceController');
    Route::post('/updatePassword', 'ResetPasswordController@updatePassword')->name('update.password');
    Route::post('/invoice/states/{id}/{page?}','InvoiceController@states')->name('invoice.states');
    Route::get('/livesearch', 'LiveSearchController@action')->name('live_search.action');
    Route::get('/export', 'ExportController@export')->name('invoice.export');
    Route::get('/vatValidator', 'vatValidatorController@action')->name('vatValidator.action');
    Route::get('/generate-html-to-pdf/{email?}', 'HtmlToPDFController@index')->name('generate-pdf');
    Route::get('/customer/showInvoice/{id}/{page?}', 'InvoiceController@show')->name('customer_show_invoice');
    Route::get('/customer/editInvoicing/{id}/{page?}', 'InvoiceController@edit')->name('customer_edit_invoice');
    Route::post('/customer/stateInvoice/{id}/{page?}', 'InvoiceController@states')->name('customer_states_invoice');
});

app/Models/Invoice.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    protected $table = 'invoices';
    protected $primaryKey = 'invoice_id';

    static $rules = [
        'invoice_id' => 'required',
        'customer_id' => 'required',
        'type_id' => 'required',
        'status_id' => 'required',
        'invoice_number' => 'required',
        'excl_tax' => 'required',
        'total_incl_tax' => 'required'
    ];

    protected $perPage = 5;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['invoice_id','customer_id','type_id','status_id'];


    public function customer()
    {
        return $this->hasOne('App\Models\Customer', 'customer_id', 'customer_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function item()
    {
        return $this->hasMany('App\Models\InvoicesItem', 'item_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function status()
    {
        return $this->hasOne('App\Models\InvoicesStatus', 'status_id', 'status_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function type()
    {
        return $this->hasOne('App\Models\InvoicesType', 'type_id', 'type_id');
    }
}

app/Models/InvoicesType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class InvoicesType extends Model
{
    protected $table = 'invoices_types';
    protected $primaryKey = 'type_id';

    public function invoice()
    {
        return $this->belongsToMany(Invoice::class);
    }
}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use App\Mail\SentMail;
use App\Models\City;
use App\Models\Company;
use App\Models\Country;
use App\Models\Customer;
use App\Models\Invoice;
use App\Models\InvoicesItem;
use App\Models\InvoicesStatus;
use App\Models\InvoicesType;
use App\Models\ZipCode;
use Barryvdh\DomPDF\Facade as PDF;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use RealRashid\SweetAlert\Facades\Alert;
use App\Http\Controllers\HtmlToPDFController;
use function MongoDB\BSON\fromJSON;

class InvoiceController extends Controller
{
    protected $reportingService;

    public function __construct()
    {
        //
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $invoices = Invoice::where('status_id','!=',10)->get();
        $tab_years = [];
        $i = 0;
        foreach ($invoices as $invoice){
            $year = date('Y', strtotime($invoice->date));
            if(!in_array($year, $tab_years)){
                $tab_years[$i] =+ $year;
            }
            $i++;
        }

        $archives = Invoice::where('status_id', '=', 10)->get();

        if($archives->isEmpty()){
            $archive = false;
        }else{
            $archive = true;
        }

        return view('invoice.index', compact('invoices', 'tab_years', 'archive'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('invoice.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id,$page='invoice')
    {
        $invoice = Invoice::find($id);
        if (empty($invoice)) {
            Alert::error('Invoicing not found 2');

            return redirect(route('invoice.index'));
        }

        $company = Company::find(1);
        $items = InvoicesItem::all()->where('invoice_id', $id);

        $status = $invoice->status_id;
        $type = $invoice->type_id;
        if($status === 7){
            $status_1 = InvoicesStatus::find(8);
            $status_2 = InvoicesStatus::find(6);
        }elseif($status === 8){
            $status_1 = InvoicesStatus::find(2);
            $status_2 = null;
        }elseif(($status === 2) || ($status === 9)){
            if($type === 1){
                $status_1 = InvoicesStatus::find(1);
                $status_2 = InvoicesStatus::find(9);
            }elseif($type === 2){
                $status_1 = InvoicesStatus::find(4);
                $status_2 = InvoicesStatus::find(3);
            }elseif($type === 3){
                $status_1 = InvoicesStatus::find(4);
                $status_2 = null;
            }
        }elseif($status === 3){
            $status_1 = InvoicesStatus::find(3);
            $status_2 = null;
        }elseif($status === 4){
            $status_1 = InvoicesStatus::find(4);
            $status_2 = null;
        }elseif($status === 6){
            $status_1 = InvoicesStatus::find(6);
            $status_2 = null;
        }else{
            $status_1 = InvoicesStatus::find(1);
            $status_2 = null;
        }

        if($page === 'customer'){
            return view('customer.showInvoice', compact('invoice', 'items', 'status_1', 'status_2', 'company'));
        }else{
            return view('invoice.show', compact('invoice', 'items', 'status_1', 'status_2', 'company'));
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id, $page='invoice')
    {
        $invoice = Invoice::find($id);

        if (empty($invoice) || ($invoice->status_id != 7)) {
            Alert::error('This billing cannot be modified.');
            return redirect(route('invoice.index'));
        }else{
            if($page === 'customer'){
                return view('customer.editInvoicing', compact('id'));
            }else{
                return view('invoice.edit', compact('id'));
            }
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function states(Request $request, $id, $page='invoice'){
        $company = Company::find(1);
        $invoice = Invoice::find($id);
        if (empty($invoice)) {
            Alert::error('Invoicing not found');

            return redirect(route('invoice.index'));
        }
        $items = InvoicesItem::all()->where('invoice_id', $invoice->invoice_id);
        $type = InvoicesType::find($invoice->type_id);
        $customer = Customer::find($invoice->customer_id);
        $email = $customer->email;
        $first_name = $customer->first_name;
        $last_name = $customer->last_name;
        $country = Country::find($customer->country_id);
        $zip = ZipCode::find($customer->zip_code_id);
        $city = City::find($customer->city_id);
        $invoice_date = $invoice->date;

        $invoicing_number = $invoice->invoice_number;

        $type_id = $invoice->type_id;
        $input = $request->input('action');
        $new_status = (int) $input;
        if($new_status === 8){
            $invoice->status_id = $new_status;
            if($type_id === 1){
                $billing_number = $this->billing_number($type_id, $invoice_date);
                $invoice->invoice_number = $billing_number;
                Alert::success("Invoice created");
            }elseif($type_id === 2){
                $billing_number = $this->billing_number($type_id, $invoice_date);
                $invoice->invoice_number = $billing_number;
                Alert::success("Quote created");
            }elseif($type_id === 3){
                $billing_number = $this->billing_number($type_id, $invoice_date);
                $invoice->invoice_number = $billing_number;
                Alert::success("Credit note created");
            }
        }elseif($new_status === 6){
            $invoice->status_id = $new_status;
        }elseif($new_status === 2){
            $pdf = PDF::loadView('invoice.pdf', compact('invoice', 'items', 'type', 'customer', 'country', 'zip', 'city','company'));
            $name = $invoicing_number.'.pdf';
            Mail::send('emails.invoicing', compact('first_name', 'last_name', 'invoicing_number', 'type'), function($message)use($email, $name, $pdf) {
                $message->from('mathieu.goffin@matg.be')
                    ->to($email)
                    ->cc('mathieu.goffin@matg.be')
                    ->subject('SimpleWork')
                    ->attachData($pdf->output(), $name);
            });
            Alert::success("The email was sent");
            $invoice->status_id = $new_status;
        }elseif($new_status === 9){
            $pdf = PDF::loadView('invoice.reminder', compact('invoice', 'items', 'type', 'customer', 'country', 'zip', 'city','company'));
            $name = $invoicing_number.'.pdf';
            Mail::send('emails.reminder', compact('first_name', 'last_name', 'invoicing_number', 'type'), function($message)use($email, $name, $pdf) {
                $message->from('mathieu.goffin@matg.be')
                    ->to($email)
                    ->cc('mathieu.goffin@matg.be')
                    ->subject('SimpleWork : Reminder')
                    ->attachData($pdf->output(), $name);
            });
            Alert::success("The email was sent");
            $invoice->status_id = $new_status;
        }elseif($new_status === 3 && $type_id ===2){
            $invoice->status_id = $new_status;
        }elseif($new_status === 4 && (($type_id === 2) || ($type_id === 3))){
            $invoice->status_id = $new_status;
        }elseif($type_id === 1){
            $invoice->status_id = $new_status;
        }

        $invoice->save();

        if($page === 'customer'){
            return $this->show($id, $page);
        }else{
            return $this->show($id);
        }
    }

    public function billing_number($type, $invoice_date){
        $year = date('Y', strtotime($invoice_date));

        $count_invoice = Invoice::where('type_id',$type)
            ->whereNotNull('invoice_number')
            ->whereYear('date', $year)
            ->count();
        $n_invoice = $count_invoice + 1;
        $digit_n_invoice = strlen($n_invoice);
        $count_zero = 4 - $digit_n_invoice;
        $str_zero = "";
        for ($i=0; $i<$count_zero; $i++){
            $str_zero = "0".$str_zero;
        }

        if($type === 1){
            $billing_number = "I.".$year.".".$str_zero.$n_invoice;
            return $billing_number;
        }elseif($type === 2){
            $billing_number = "Q.".$year.".".$str_zero.$n_invoice;
            return $billing_number;
        }elseif($type === 3){
            $billing_number = "CN.".$year.".".$str_zero.$n_invoice;
            return $billing_number;
        }
    }
}

resources/views/invoice/create.blade.php
@extends('layouts.app')

@section('content')
    <div id="invoice-create" class="pb-2 mb-3 h-100 mx-2 d-flex flex-column align-items-center">
        <div class="row my-1 w-100">
            <div class="col-1">
                <a href="{{ url()->previous() }}" class="btn btn-primary">Back</a>
            </div>
        </div>
        <div id="appInvoice" class="sw_form row w-100 h-100 mt-4 d-flex flex-column">
            <form-invoice></form-invoice>
        </div>
    </div>
@endsection

resources/views/invoice/edit.blade.php
@extends('layouts.app')

@section('content')
    <div id="invoice-edit" class="pb-2 mb-3 h-100 mx-2 d-flex flex-column align-items-center">
        <div class="row my-1 w-100">
            <div class="col-1">
                <a href="{{ URL::previous() }}" class="btn btn-primary ml-3">Back</a>
            </div>
        </div>
        @include('editInvoicing')
    </div>
@endsection

resources/views/invoice/index.blade.php
@extends('layouts.app')

@section('content')
    <div id="invoice-index" class="pb-2 mb-3 h-100 mx-2 d-flex justify-content-center flex-column align-items-center">
        <div class="row my-1 w-100 justify-content-between">
            <div class="col-md-2">
                <a href="{{ route('invoice.create') }}" class="btn btn-primary">Add new</a>
            </div>
            <div class="d-flex">
                <form method="get" action="{{ route('invoice.export') }}">
                    <div class="col-md-1 mr-3 d-flex">
                        <select name="years" id="years">
                            <option value="none"></option>
                            @foreach ($tab_years as $year)
                                <option value="{{ $year }}">{{ $year }}</option>
                            @endforeach
                        </select>
                        <button type="submit" class="btn btn-primary" disabled id="btn-export">Export</button>
                    </div>
                </form>
            </div>
        </div>

        <div id="container-invoice" class="h-auto w-100 mt-4">
            @include('tab_billing')
        </div>
    </div>
@endsection

resources/views/invoice/invoiceShow.blade.php
<div id="invoice-show" class="pb-2 mb-3 h-100 mx-2 d-flex justify-content-center flex-column align-items-center">
    <div class="row my-1 w-100">
        @if(strpos(url()->previous(), 'customer'))
            <a href="{{ route('customer.show',$invoice->customer_id) }}" class="btn btn-primary ml-3">Back</a>
        @else
            <a href="{{ route('invoice.index') }}" class="btn btn-primary ml-3">Back</a>
        @endif
    </div>
    <div id="container-invoice" class="h-auto w-100 mt-4">
        <div class="row d-flex justify-content-between">
            <div class="ml-3">
                <label class="primary_label">STATUS : </label>
                <span class="
                    @if($invoice->status_id === 7)
                        draft
                    @elseif($invoice->status_id === 4)
                        validated
                    @elseif($invoice->status_id === 2)
                        sent
                    @elseif($invoice->status_id === 1)
                        paid
                    @elseif($invoice->status_id === 8)
                        signed
                    @elseif($invoice->status_id === 3)
                        rejected
                    @elseif($invoice->status_id === 6)
                        deleted
                    @elseif($invoice->status_id === 9)
                        reminder
                    @endif
                    ">
                            {{ strtoupper($invoice->status->status_name) }}
                        </span>
            </div>
            <div class="invoice_show btn-group" role="group">
                <form
                    action="
                        @if(strpos(url()->current(), 'customer'))
                            {{ route('customer_states_invoice',['id'=>$invoice->invoice_id,'page'=>'customer']) }}
                        @else
                            {{ route('invoice.states',$invoice->invoice_id) }}
                        @endif
                    "
                    method="post">
                    {{ csrf_field() }}

                    @if(($invoice->status_id != 1) && ($invoice->status_id != 4) && ($invoice->status_id != 3) && ($invoice->status_id != 6))
                        <button type="submit" name="action" value="{{ $status_1->status_id }}" class="btn btn-secondary {{ $status_1->status_name }}">
                            @if($status_1->status_id === 4)
                                Validate
                            @elseif($status_1->status_id === 2)
                                Send
                            @elseif($status_1->status_id === 1)
                                Paid
                            @elseif($status_1->status_id === 8)
                                Sign
                            @endif
                        </button>
                    @endif

                    @if($status_2)
                        <div class="btn-group" role="group">
                            <button id="btnGroupDrop" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                            <div id="invoice_show_dropdown-menu" class="dropdown-menu" aria-labelledby="btnGroupDrop">
                                @if($status_2)
                                    <button type="submit" name="action" value="{{ $status_2->status_id }}" class="btn btn-secondary {{ $status_2->status_name }}" >
                                        @if($status_2->status_id === 3)
                                            Reject
                                        @elseif($status_2->status_id === 6)
                                            Delete
                                        @elseif($status_2->status_id === 9)
                                            Reminder
                                        @endif
                                    </button>
                                @endif
                            </div>
                        </div>
                    @endif
                </form>
                @if($invoice->status_id === 7)
                    <div class="col-md-4">
                        @if(strpos(url()->current(), 'customer'))
                            <a href="{{ route('customer_edit_invoice', ['id'=>$invoice->invoice_id,'page'=>'customer']) }}" class="btn btn-warning">Edit</a>
                        @else
                            <a href="{{ route('invoice.edit', $invoice->invoice_id) }}" class="btn btn-warning">Edit</a>
                        @endif
                    </div>
                @elseif($invoice->status_id != 3 && $invoice->status_id != 6 && $invoice->status_id != 7)
                    <div class="col-md-4">
                        <a href="{{ route('generate-pdf',['download'=>'pdf', 'name'=>$invoice->invoice_number, 'invoice'=>$invoice->invoice_id]) }}" class="btn">
                            <img class="icon_pdf" src="/img/icons/invoice/icon_pdf.png" alt="Icon représentant un PDF" title="Download PDF">
                        </a>
                    </div>
                @endif
            </div>
        </div>
        <div class="hr"></div>
        <div class="row d-flex justify-content-between pr-5 pl-5">
            <div id="infos_company" class="card-infos-invoice col-md-3">
                <div>
                    <h1>{{ ucfirst($company->company_name) }}</h1>
                    <address>
                        <street>{{ ucfirst($company->street_address) }}, {{ ucfirst($company->number_address) }}</street><br>
                        @if(($company->box_address) == '')

                        @else
                            <street>Box {{ ucfirst($company->box_address) }}</street><br>
                        @endif
                        <city>{{ ucfirst($company->zip_code) }} - {{ ucfirst($company->city) }}</city><br>
                        <city>{{ ucfirst($company->country) }}</city><br>
                        <phone>{{ ucfirst($company->phone_number) }}</phone><br>
                        <email>{{ $company->email }}</email><br>
                        <vat>{{ $company->vat }}</vat>
                    </address>
                </div>
            </div>
            <div id="infos_invoice" class="card-infos-invoice col-md-3">
                <h1>{{ strtoupper($invoice->type->type_name) }}</h1>
                <div class="d-flex justify-content-around">
                        <span>
                            @if($invoice->invoice_number)
                                <h5 class="secondary_label">Invoice number :</h5>
                            @endif
                            <h5 class="secondary_label">Date :</h5>
                        </span>
                    <span>
                            @if($invoice->invoice_number)
                            <h5>{{ strtoupper($invoice->invoice_number) }}</h5>
                        @endif
                            <h5>{{ date('d-m-Y', strtotime($invoice->date))}}</h5>
                        </span>
                </div>
            </div>
        </div>
        <div class="row d-flex justify-content-between mt-5 pl-5">
            <div id="infos_customer" class="card-infos-invoice col-md-3">
                <label class="primary_label">TO</label>
                <div class="d-flex justify-content-around">
                    <table class="w-100 ml-4">
                        <tr>
                            <th>Campany :</th>
                            <td>{{ ucfirst($invoice->customer->company) }}</td>
                        </tr>
                        <tr>
                            <th>VAT :</th>
                            <td>{{ ucfirst($invoice->customer->vat) }}</td>
                        </tr>
                        <tr>
                            <th>Name :</th>
                            <td>{{ ucfirst($invoice->customer->first_name) . ' ' . ucfirst($invoice->customer->last_name) }}</td>
                        </tr>
                        <tr>
                            <th>Address :</th>
                            <td>{{ ucfirst($invoice->customer->street_address) . ', ' . ucfirst($invoice->customer->number_address) }}</td>
                        </tr>
                        <tr>
                            <th>ZIP, City :</th>
                            <td>{{ ucfirst($invoice->customer->zip->zip_code) . ', ' . ucfirst($invoice->customer->city->city_name) }}</td>
                        </tr>
                        <tr>
                            <th>Country :</th>
                            <td>{{ ucfirst($invoice->customer->country->country_name) }}</td>
                        </tr>
                        <tr>
                            <th>Phone :</th>
                            <td>{{ ucfirst($invoice->customer->phone_number) }}</td>
                        </tr>
                        <tr>
                            <th>Email :</th>
                            <td>{{ $invoice->customer->email }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>

        <!-- Table items -->
        <div id="infos_items" class="row d-flex mt-5 pr-5 pl-5">
            <table class="table_items table table-striped table-dark">
                <thead>
                <tr>
                    <th scope="col">Quantity</th>
                    <th scope="col">Description</th>
                    <th scope="col">Price</th>
                    <th scope="col">Amount</th>
                </tr>
                </thead>
                <tbody>
                @foreach($items as $item)
                    <tr>
                        <td>{{ $item->quantity }}</td>
                        <td>{{ ucfirst($item->description) }}</td>
                        <td>{{ number_format($item->price, 2, ',', ' ') }} €</td>
                        <td>{{ number_format($item->amount, 2, ',', ' ') }} €</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <div id="resume_total" class="col-12 d-flex justify-content-end">
                <div class="col-3">
                    <ul>
                        <li>Excl tax : <span class="total">{{ number_format($invoice->excl_tax, 2, ',', ' ') }} €</span></li>
                        <li>VAT : <span class="total">{{ $invoice->vat }} %</span></li>
                        <li>Total : <span class="total"><b>{{ number_format($invoice->total_incl_tax, 2, ',', ' ') }} €</b></span></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row d-flex flex-column mt-5 pl-5">
            <label class="primary_label">CONDITIONS</label>

            <!-- term of validity Field -->
            @if($invoice->type_id === 2)
                <div id="infos_validity" class="card-infos-invoice col-md-3">
                    <label class="secondary_label">Term of validity</label>
                    <p>{{ ucfirst($invoice->quote_term_validity) }}</p>
                </div>
            @endif

        <!-- Terms of payment Field -->
            @if($invoice->type_id === 1)
                <div id="infos_payment" class="card-infos-invoice col-md-3 mt-3">
                    <label class="secondary_label">Terms of payment</label>
                    <p>{{ ucfirst($invoice->invoice_terms_payment) }}</p>
                </div>
            @endif

        <!-- Comment Field -->
            @if($invoice->comment)
                <div id="infos_comment" class="card-infos-invoice col-md-3 mt-3">
                    <label class="secondary_label">Comment</label>
                    <p>{{ ucfirst($invoice->comment) }}</p>
                </div>
            @endif
        </div>
    </div>
</div>

resources/views/invoice/show.blade.php
@extends('layouts.app')

@section('content')
    @include('invoice.invoiceShow')
@endsection