routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

Route::get('/', function ($guard = null){
    if(Browser::isIE() || Browser::isEdge()){
        return view('auth/bad_browser');
    }elseif (Auth::guard($guard)->check()) {
        return redirect('/home');
    }
    else{
        return view('auth/login');
    }
});

Route::get('/bad_browser', function (){
    return view('auth/bad_browser');
})->name('bad.browser');

Auth::routes();

Route::group(['middleware' => ['web','auth'],'prefix'=>''], function (){
    Route::get('/home', 'HomeController@index')->name('home.index');
    Route::resource('settings', 'SettingsController');
    Route::resource('customer','CustomerController');
    Route::resource('invoice','InvoiceController');
    Route::post('/updatePassword', 'ResetPasswordController@updatePassword')->name('update.password');
    Route::post('/invoice/states/{id}/{page?}','InvoiceController@states')->name('invoice.states');
    Route::get('/livesearch', 'LiveSearchController@action')->name('live_search.action');
    Route::get('/export', 'ExportController@export')->name('invoice.export');
    Route::get('/vatValidator', 'vatValidatorController@action')->name('vatValidator.action');
    Route::get('/generate-html-to-pdf/{email?}', 'HtmlToPDFController@index')->name('generate-pdf');
    Route::get('/customer/showInvoice/{id}/{page?}', 'InvoiceController@show')->name('customer_show_invoice');
    Route::get('/customer/editInvoicing/{id}/{page?}', 'InvoiceController@edit')->name('customer_edit_invoice');
    Route::post('/customer/stateInvoice/{id}/{page?}', 'InvoiceController@states')->name('customer_states_invoice');
});

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $table = 'customers';
    protected $primaryKey = 'customer_id';
    protected $fillable = [
        'first_name',
        'last_name',
        'birth_date',
        'email',
        'phone_number',
        'company',
        'vat',
        'street_address',
        'number_address',
        'box_address',
        'country_id',
        'city_id',
        'zip_code_id'
    ];

    public function invoice()
    {
        return $this->belongsToMany('App\Models\Invoice', 'invoices');
    }

    public function city(){
        return $this->hasOne('App\Models\City', 'city_id', 'city_id');
    }

    public function country(){
        return $this->hasOne('App\Models\Country','country_id','country_id');
    }

    public function zip(){
        return $this->hasOne('App\Models\ZipCode','zip_code_id','zip_code_id');
    }

    public function getFullNameAttribute(){
        return ucfirst($this->first_name). ' ' .ucfirst($this->last_name);
    }

    public static function rulesUpdates($id){
        return [
            'first_name' => 'required',
            'last_name' => 'required',
            'birth_date' => 'required',
            'vat' => 'nullable|unique:customers,customer_id,'.$id.',customer_id',
            'company' => 'nullable|unique:customers,customer_id,'.$id.',customer_id',
            'email' => 'required|email|unique:customers,customer_id,'.$id.',customer_id',
            'phone_number' => 'required|numeric',
            'street_address' => 'required',
            'number_address' => 'required',
            'country_id' => 'required',
            'city_id' => 'required',
            'zip_code_id' => 'required'
        ];
    }
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CustomerRequest;
use App\Models\City;
use App\Models\Country;
use App\Models\Customer;
use App\Models\Invoice;
use App\Models\InvoicesItem;
use App\Models\InvoicesStatus;
use App\Models\InvoicesType;
use App\Models\ZipCode;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use MercurySeries\Flashy\Flashy;
use RealRashid\SweetAlert\Facades\Alert;

class CustomerController extends Controller
{
    public function __construct()
    {
        //
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customers = Customer::all()->sortBy('company');

        return view('customer.index', compact('customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $customers = Customer::all();
        $countries = Country::all()->pluck('country_name','country_id');
        $cities = City::all();
        $zip_codes = ZipCode::all();

        return view('customer.create', compact('customers','countries', 'zip_codes', 'cities'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CustomerRequest $request)
    {
        $customer = new Customer();
        $customer->first_name = $request->first_name;
        $customer->last_name = $request->last_name;
        $customer->birth_date = $request->birth_date;
        $customer->email = $request->email;
        $customer->phone_number = $request->phone_number;
        if(isset($request->company)){
            $customer->company = $request->company;
        }else{
            $customer->company = 'Individual customers';
        }
        if(isset($request->vat)){
            $customer->vat = $request->vat;
        }else{
            $customer->vat = '/';
        }
        $customer->street_address = $request->street_address;
        $customer->number_address = $request->number_address;
        $customer->box_address = $request->box_address;
        $customer->country_id = $request->country_id;
        $customer->zip_code_id = $request->zip_code_id;
        $customer->city_id = $request->city_id;
        $customer->save();

        Alert::success('Customer add');

        return $this->show($customer->customer_id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $customer = Customer::find($id);
        if (empty($customer)) {
            Alert::error('Customers not found');

            return redirect(route('customer.index'));
        }
        $countries = Country::all()->pluck('country_name','country_id');
        $cities = City::all()->pluck('city_name','city_id');
        $zip = ZipCode::all()->pluck('zip_code','zip_code_id');
        $invoices = Invoice::all()->where('customer_id', $id);

        return view('customer.show',compact('customer','countries', 'cities', 'zip','invoices'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $customer = Customer::find($id);
        if (empty($customer)) {
            Alert::error('Customers not found');

            return redirect(route('customer.index'));
        }
        $countries = Country::all()->pluck('country_name','country_id');
        $customer_city = City::all()->where('city_id', $customer->city_id);
        $cities = City::all();
        $zip_codes = ZipCode::all();
        $customer_zip = ZipCode::all()->where('zip_code_id', $customer->zip_code_id);
        $invoices = Invoice::all()->where('customer_id', $id);

        return view('customer.edit',compact('customer','countries', 'cities', 'zip_codes','invoices', 'customer_city', 'customer_zip'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate(Customer::rulesUpdates($id));
        $customer = Customer::find($id);

        if (empty($customer)) {
            Alert::error('Customers not found');

            return redirect(route('customer.index'));
        }

        $customer->first_name = $request->first_name;
        $customer->last_name = $request->last_name;
        $customer->birth_date = $request->birth_date;
        $customer->email = $request->email;
        $customer->phone_number = $request->phone_number;
        if(isset($request->company)){
            $customer->company = $request->company;
        }else{
            $customer->company = 'Individual customers';
        }
        if(isset($request->vat)){
            $customer->vat = $request->vat;
        }else{
            $customer->vat = '/';
        }
        $customer->street_address = $request->street_address;
        $customer->number_address = $request->number_address;
        $customer->box_address = $request->box_address;
        $customer->country_id = $request->country_id;
        $customer->zip_code_id = $request->zip_code_id;
        $customer->city_id = $request->city_id;
        $customer->save();

        Alert::success("Customer updated");

        return redirect(route('customer.show', $id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $customer = Customer::find($id);
        if (empty($customer)) {
            Alert::error('Customers not found');

            return redirect(route('customer.index'));
        }

        $invoices = Invoice::all()->where('customer_id', $id);

        if ($invoices->isNotEmpty()){
            Alert::error('This customer can\'t deleted because he has one or more invoicing linked to his account.');
            return $this->show($id);
        }else{
            $customer->delete($id);
            Alert::success('Customers deleted successfully.');
            return redirect(route('customer.index'));
        }
    }
}

resources/views/customer/create.blade.php
@extends('layouts.app')

@section('content')
    <div id="customer-create" class="pb-2 mb-3 h-100 mx-2 d-flex justify-content-center flex-column align-items-center">
        <div class="row my-1 w-100">
            <a href="{{ route('customer.index') }}" class="btn btn-primary ml-3">Back</a>
        </div>
        <div class="sw_form row w-100 mt-4 d-flex flex-column">
            {!! Form::open(['route' => 'customer.store', 'method' => 'post']) !!}
                @include('customer.form')
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/customer/edit.blade.php
@extends('layouts.app')

@section('content')
    <div id="customer-edit" class="pb-2 mb-3 h-100 mx-2 d-flex justify-content-center flex-column align-items-center">
        <div class="row my-1 w-100">
            <a href="{{ route('customer.show', $customer->customer_id) }}" class="btn btn-primary ml-3">Back</a>
        </div>
        <div class="sw_form row w-100 mt-4 d-flex flex-column">
            {!! Form::model($customer, ['route' => ['customer.update', $customer->customer_id], 'method' => 'PATCH']) !!}
            @include('customer.form')
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/customer/editInvoicing.blade.php
@extends('layouts.app')

@section('content')
    <div id="invoice-edit" class="pb-2 mb-3 h-100 mx-2 d-flex flex-column align-items-center">
        <div class="row my-1 w-100">
            <div class="col-1">
                {{--                <a href="{{ route('invoice.index') }}" class="btn btn-primary ml-3">Back</a>--}}
                <a href="{{ URL::previous() }}" class="btn btn-primary ml-3">Back</a>
            </div>
        </div>
        @include('editInvoicing')
    </div>
@endsection

resources/views/customer/form.blade.php
    <div class="form-row">
        <div class="form-group col-lg-6">
            {!! Form::label('company', 'Company', ['class' => 'control-label label']) !!}
            {!! Form::text('company', null, ['class' => 'form-control'. ($errors->has('company') ? ' is-invalid' : ''), 'placeholder'=>'Company']) !!}
            {!! $errors->first('company', '<p class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group col-lg-6">
            {!! Form::label('vat', 'VAT number', ['class' => 'control-label']) !!}
            {!! Form::text('vat',null,['class' => 'form-control'. ($errors->has('vat') ? ' is-invalid' : ''), 'placeholder'=>'VAT']) !!}
            {!! $errors->first('vat', '<p class="invalid-feedback">:message</p>') !!}
            <span id="vat_valid" class="disabled"><img src="/img/icons/customer/form_validation/true.png" alt="">valid VAT number</span>
            <span id="vat_invalid" class="disabled"><img src="/img/icons/customer/form_validation/false.png" alt="">invalid VAT number</span>
        </div>
    </div>
    <div class="hr">&nbsp;</div>
    <div class="form-row">
        <div class="form-group col-lg-4">
            {!! Form::label('last_name', 'Last name *', ['class' => 'control-label']) !!}
            {!! Form::text('last_name', null, ['class' => 'form-control'. ($errors->has('last_name') ? ' is-invalid' : ''), 'placeholder'=>'Last name']) !!}
            {!! $errors->first('last_name', '<p class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group col-lg-4">
            {!! Form::label('first_name', 'First name *', ['class' => 'control-label']) !!}
            {!! Form::text('first_name', null, ['class' => 'form-control'. ($errors->has('first_name') ? ' is-invalid' : ''), 'placeholder'=>'First name']) !!}
            {!! $errors->first('first_name', '<p class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group col-lg-4">
            {!! Form::label('birth_date', 'Birth date *', ['class' => 'control-label']) !!}
            {!! Form::date('birth_date', null, ['class'=>'form-control'. ($errors->has('birth_date') ? ' is-invalid' : '')]) !!}
            {!! $errors->first('birth_date', '<p class="invalid-feedback">:message</p>') !!}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-lg-4">
            {!! Form::label('street', 'Street *', ['class' => 'control-label']) !!}
            {!! Form::text('street_address', null, ['class' => 'form-control'. ($errors->has('street_address') ? ' is-invalid' : ''), 'placeholder'=>'Street']) !!}
            {!! $errors->first('street_address', '<p class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group col-lg-4">
            {!! Form::label('number', 'Number *', ['class' => 'control-label']) !!}
            {!! Form::text('number_address', null, ['class' => 'form-control'. ($errors->has('number_address') ? ' is-invalid' : ''), 'placeholder'=>'Number']) !!}
            {!! $errors->first('number_address', '<p class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group col-lg-4">
            {!! Form::label('box', 'Box', ['class' => 'control-label']) !!}
            {!! Form::text('box_address', null, ['class' => 'form-control', 'placeholder'=>'Box']) !!}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-lg-4">
            {!! Form::label('country', 'Country *', ['class' => 'control-label']) !!}
            {!! Form::select('country_id', $countries , null , ['class' => 'form-control'. ($errors->has('country_id') ? ' is-invalid' : ''),'placeholder'=>'','id'=>'country']) !!}
            {!! $errors->first('country_id', '<p class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group col-lg-4">
            {!! Form::label('zip', 'Zip *', ['class' => 'control-label']) !!}
            <select class="form-control" name="zip_code_id" id="zip">
                @if($customer_zip ?? '')
                    @foreach($customer_zip as $c_zip)
                        <option selected value="{{ $c_zip->zip_code_id }}">{{ $c_zip->zip_code }}</option>
                    @endforeach
                    @foreach($zip_codes as $zip)
                        <option value="{{ $zip->zip_code_id }}" country="{{ $zip->country_id }}">{{ $zip->zip_code }}</option>
                    @endforeach
                @else
                    <option value=""></option>
                    @foreach($zip_codes as $zip)
                        <option value="{{ $zip->zip_code_id }}" country="{{ $zip->country_id }}">{{ $zip->zip_code }}</option>
                    @endforeach
                @endif
            </select>
            {!! $errors->first('zip_code_id', '<p class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group col-lg-4">
            {!! Form::label('city', 'City *', ['class' => 'control-label']) !!}
            <select class="form-control" name="city_id" id="city">
                @if($customer_city ?? '')
                    @foreach($customer_city as $c_city)
                        <option selected value="{{ $c_city->city_id }}">{{ $c_city->city_name }}</option>
                    @endforeach
                    @foreach($cities as $city)
                        <option value="{{ $city->city_id }}" zip="{{ $city->zip_code_id }}" country="{{ $city->country_id }}">{{ $city->city_name }}</option>
                    @endforeach
                @else
                    <option value=""></option>
                    @foreach($cities as $city)
                        <option value="{{ $city->city_id }}" zip="{{ $city->zip_code_id }}" country="{{ $city->country_id }}">{{ $city->city_name }}</option>
                    @endforeach
                @endif
            </select>
            {!! $errors->first('city_id', '<p class="invalid-feedback">:message</p>') !!}
        </div>

    </div>
    <div class="form-row">
        <div class="form-group col-lg-4">
            {!! Form::label('phone_number', 'Phone number *', ['class' => 'control-label']) !!}
            {!! Form::text('phone_number', null, ['class' => 'form-control'. ($errors->has('phone_number') ? ' is-invalid' : ''),'placeholder'=>'Phone number']) !!}
            {!! $errors->first('phone_number', '<p class="invalid-feedback">:message</p>') !!}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-lg-4">
            {!! Form::label('email', 'Email *', ['class' => 'control-label']) !!}
            {!! Form::email('email', null, ['class' => 'form-control'. ($errors->has('email') ? ' is-invalid' : ''), 'placeholder'=>'Email']) !!}
            {!! $errors->first('email', '<p class="invalid-feedback">:message</p>') !!}
        </div>
    </div>
    <div class="form-row d-flex justify-content-center">
        {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    </div>

resources/views/customer/index.blade.php
@extends('layouts.app')

@section('content')
    <div id="customer-index" class="pb-2 mb-3 h-100 mx-2 d-flex justify-content-start flex-column align-items-center">
        <div class="row my-1 w-100">
            <div class="col-1">
                <a href="{{ route('customer.create') }}" class="btn btn-primary">Add new</a>
            </div>
            <div class="col-10">
                <form id="live-search" onsubmit="return(false);" method="post">
                    <input type="text" class="form-control" id="search_customer" value="" placeholder="Search customer data. For all customers, type : all">
                </form>
            </div>
        </div>
        <div id="container-customer" class="row mt-5 container-fluid">
            <div id="container-card-customer" class="row w-100 h-100">
                <div id="n_customer" class="result_ajax_n_customer col-12 h-100"></div>
                <div id="card-customer" class="result_ajax row col-md-12 h-100 mb-4 disabled"></div>
            </div>
        </div>
    </div>
@endsection

resources/views/customer/show.blade.php
@extends('layouts.app')

@section('content')
    <div id="customer-show" class="pb-2 mb-3 h-100 mx-2 d-flex justify-content-center flex-column align-items-center">
        <div class="row my-1 w-100">
            <a href="{{ route('customer.index') }}" id="back_index_customer" class="btn btn-primary ml-3">Back</a>
        </div>
        <div id="customer-info" class="h-auto w-100 mt-4">
            <div id="container-info-customer">
                <div class="row">
                    <div class="col-lg-6">
                        <h5>Company name</h5>
                        <p>{{ $customer->company }}</p>
                    </div>
                    <div class="col-lg-6">
                        <h5>VAT number</h5>
                        <p>{{ $customer->vat }}</p>
                    </div>
                </div>
                <div class="hr">&nbsp;</div>
                <div class="row">
                    <div class="col-lg-4">
                        <h5>Last name</h5>
                        <p>{{ $customer->last_name }}</p>
                    </div>
                    <div class="col-lg-4">
                        <h5>First name</h5>
                        <p>{{ $customer->first_name }}</p>
                    </div>
                    <div class="form-group col-lg-4">
                        <h5>Birth date</h5>
                        <p>{{ $customer->birth_date }}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4">
                        <h5>Street</h5>
                        <p>{{ $customer->street_address }}</p>
                    </div>
                    <div class="col-lg-4">
                        <h5>Number</h5>
                        <p>{{ $customer->number_address }}</p>
                    </div>
                    <div class="form-group col-lg-4">
                        <h5>Box</h5>
                        <p>
                            @if(($customer->box_address) == '')
                                /
                            @else
                                {{ $customer->box_address }}
                            @endif
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4">
                        <h5>Country</h5>
                        <p>{{ $customer->country->country_name }}</p>
                    </div>
                    <div class="form-group col-lg-4">
                        <h5>Zip code</h5>
                        <p>{{ $customer->zip->zip_code }}</p>
                    </div>
                    <div class="form-group col-lg-4">
                        <h5>City</h5>
                        <p>{{ $customer->city->city_name }}</p>
                    </div>

                </div>
                <div class="form-row">
                    <div class="form-group col-lg-4">
                        <h5>Telephone number</h5>
                        <p>{{ $customer->phone_number }}</p>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-lg-4">
                        <h5>Email</h5>
                        <p>{{ $customer->email }}</p>
                    </div>
                </div>
            </div>
            <div id="container_btn_show_customer" class="row d-flex flex-row justify-content-center align-items-center">
                <a href="{{ route('customer.edit',$customer->customer_id) }}" id="btn-edit-customer" class="btn btn-secondary mr-1">Edit</a>
                <form action="{{ route('customer.destroy',$customer->customer_id) }}" method="post">
                    @method('delete')
                    {{ csrf_field() }}
                    <input id="btn-delete-customer" type="submit" class="btn btn-danger" value="Delete">
                </form>
            </div>
        </div>
        <div id="customer-info-invoices" class="h-auto w-100 mt-4">
            <h5 class="primary_label">Invoicing</h5>
            @include('tab_billing')
        </div>
    </div>
@endsection

resources/views/customer/showInvoice.blade.php
@extends('layouts.app')

@section('content')
    @include('invoice.invoiceShow')
@endsection